name: Secret Demo
on: [push]
jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Secret API_KEY
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -n "$MY_API_KEY" ]; then
            echo "API_KEY configurado"
          else
            echo "API_KEY nao encontrado"
          fi